- directory: ./img/blog/*.*
  width: 240
  height: 240

- directory: ./img/mentors/*.*
  width: 240
  height: 240

- directory: ./img/projects/*.*
  width: 240
  height: 240

- directory: ./img/students/*.*
  width: 240
  height: 240

